name: Code Quality
permissions:
  contents: read
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read

jobs:
  lint:
    uses: bcgov/des-git-workflows/.github/workflows/js-css-lint.yml@main
    with:
      node_version: '^22.18.0'