name: PHPCS Validation
permissions:
  contents: read
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  phpcs-validation:
    uses: bcgov/des-git-workflows/.github/workflows/phpcs-validate.yml@main